package dev.tmpod.staticapi.processor

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

/**
 * Tests for basic successful compilation scenarios.
 *
 * These tests verify the core functionality of the StaticApiProcessor
 * with common, expected usage patterns.
 */
class HappyPathTest : CompilationTestBase() {

    @Test
    fun testBasicInterfaceWithAutoNaming() {
        val generated = compileSourceAndAssertSuccess(
            "IFooBar.kt", "FooBar_IMPL.kt",
            """
            /**
             * API to work with foo and bar.
             */
            @StaticApi
            interface IFooBar {
                /** Makes a new foo. */
                fun makeFoo(): String

                /** Returns true if the given foo is also a bar. */
                fun isBar(foo: String): Boolean
            }
            """
        )

        // Verify object name (auto-generated by removing 'I' prefix)
        assertThat(generated).contains("object FooBar")

        // Verify delegate property
        assertContainsProperty(generated, "delegate", "IFooBar")
        assertHasAnnotation(generated, "ApiStatus.Internal")

        // Verify forwarding methods with @JvmStatic
        assertContainsMethod(generated, "makeFoo", "String")
        assertThat(generated).contains("@JvmStatic")
        assertThat(generated).contains("= delegate.makeFoo()")

        assertContainsMethod(generated, "isBar", "Boolean", "foo" to "String")
        assertThat(generated).contains("= delegate.isBar(foo)")

        // Verify KDoc preservation
        assertHasKDoc(generated, "API to work with foo and bar")
        assertHasKDoc(generated, "Makes a new foo")
        assertHasKDoc(generated, "Returns true if the given foo is also a bar")
    }

    @Test
    fun testMethodsAreForwardedCorrectly() {
        val generated = compileSourceAndAssertSuccess(
            "IApi.kt", "Api_IMPL.kt",
            """
            @StaticApi
            interface IApi {
                fun getString(): String
                fun getInt(value: Int): Int
                fun doSomething()
            }
            """
        )

        // Verify methods with return types have return statement
        assertThat(generated).contains("= delegate.getString()")
        assertThat(generated).contains("= delegate.getInt(value)")

        // Verify Unit-returning methods don't have return statement
        assertThat(generated)
            .doesNotContain("return delegate.doSomething()")
        assertThat(generated).contains("delegate.doSomething()")

        // Verify parameter passing
        assertContainsMethod(generated, "getInt", "Int", "value" to "Int")
        assertThat(generated).contains("delegate.getInt(value)")
    }

    @Test
    fun testDocCommentsArePreserved() {
        val generated = compileSourceAndAssertSuccess(
            "IDocumented.kt", "Documented_IMPL.kt",
            """
            /**
             * This is a documented API.
             * It has multiple lines.
             */
            @StaticApi
            interface IDocumented {
                /**
                 * Performs an operation.
                 * Returns the result as a string.
                 */
                fun performOperation(): String
            }
            """
        )

        // Verify class-level KDoc
        assertHasKDoc(generated, "This is a documented API")
        assertHasKDoc(generated, "It has multiple lines")

        // Verify method-level KDoc
        assertHasKDoc(generated, "Performs an operation")
        assertHasKDoc(generated, "Returns the result as a string")
    }

    @Test
    fun testMultipleMethodsWithDifferentSignatures() {
        val generated = compileSourceAndAssertSuccess(
            "IMultiMethod.kt", "MultiMethod_IMPL.kt",
            """
            @StaticApi
            interface IMultiMethod {
                fun noParams(): String
                fun singleParam(value: Int): Boolean
                fun multipleParams(a: String, b: Int, c: Double): List<String>
                fun withNullable(value: String?): String?
                fun chainedCalls(a: Int, b: String, c: Boolean): String
            }
            """
        )

        // Verify all methods are generated
        assertContainsMethod(generated, "noParams", "String")
        assertContainsMethod(generated, "singleParam", "Boolean", "value" to "Int")
        assertContainsMethod(generated, "multipleParams", "List<String>", "a" to "String", "b" to "Int", "c" to "Double")
        assertContainsMethod(generated, "withNullable", "String?", "value" to "String?")
        assertContainsMethod(generated, "chainedCalls", "String", "a" to "Int", "b" to "String", "c" to "Boolean")

        // Verify all forwarding calls
        assertThat(generated).contains("delegate.noParams()")
        assertThat(generated).contains("delegate.singleParam(value)")
        assertThat(generated).contains("delegate.multipleParams(a, b, c)")
        assertThat(generated).contains("delegate.withNullable(value)")
        assertThat(generated).contains("delegate.chainedCalls(a, b, c)")
    }
}
